### ISSUE TITLE
Mod crashes game [Fabric]

### ISSUE THREAD

**Issue by ghost** [Naxanria/itemgot#1]
[02:01:44] [main/INFO]: Loading for game Minecraft 1.14.2
[02:01:44] [main/INFO]: Fabric is preparing JARs on first launch, this may take a few seconds...
[02:01:51] [main/INFO]: [FabricLoader] Loading 2 mods: fabricloader@0.4.8+build.155, itemgot@1.0.4
[02:01:51] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.7.11 Source=file:/C:/Users/jilmh/Desktop/Main/Minecraft/MultiMC/libraries/net/fabricmc/sponge-mixin/0.7.11.36/sponge-mixin-0.7.11.36.jar Service=Knot/Fabric Env=CLIENT
[02:01:51] [main/INFO]: Compatibility level set to JAVA_8
[02:01:51] [main/INFO]: Setting user: Jilm
[02:01:54] [main/INFO]: Config file: C:\Users\jilmh\Desktop\Main\Minecraft\MultiMC\instances\1.14.2\.minecraft\.\config\itemgot\itemgot.cfg
[02:01:54] [main/INFO]: Entry for drawTotal not found, going to default value true
[02:01:54] [main/INFO]: Entry for textColour not found, going to default value ffffffff
[02:01:54] [main/INFO]: Entry for fadeTime not found, going to default value 10
[02:01:54] [main/INFO]: Entry for drawText not found, going to default value false
[02:01:54] [main/INFO]: Entry for refreshTime not found, going to default value 5
[02:01:54] [main/INFO]: Entry for x not found, going to default value 10
[02:01:54] [main/INFO]: Entry for logSize not found, going to default value 8
[02:01:54] [main/INFO]: Entry for y not found, going to default value 10
[02:01:54] [main/INFO]: Entry for textLength not found, going to default value 10
[02:01:54] [main/INFO]: Entry for fadeDelay not found, going to default value 5
[02:01:54] [main/INFO]: Entry for backgroundColour not found, going to default value 00000000
[02:01:54] [main/INFO]: Entry for updateFrequency not found, going to default value 10
---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 6/23/19 2:01 AM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors!
	at net.fabricmc.loader.entrypoint.hooks.EntrypointUtils.logErrors(EntrypointUtils.java:45)
	at net.fabricmc.loader.entrypoint.hooks.EntrypointClient.start(EntrypointClient.java:35)
	at net.minecraft.class_310.method_1503(class_310.java)
	at net.minecraft.class_310.method_1514(class_310.java:395)
	at net.minecraft.client.main.Main.main(Main.java:154)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:129)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
	Suppressed: java.lang.NoClassDefFoundError: net/fabricmc/fabric/api/event/client/ClientTickCallback
		at com.naxanria.itemgot.ItemGot.onInitialize(ItemGot.java:65)
		at com.naxanria.itemgot.ItemGot.onInitializeClient(ItemGot.java:92)
		at net.fabricmc.loader.entrypoint.hooks.EntrypointUtils.lambda$logErrors$0(EntrypointUtils.java:38)
		at java.util.ArrayList.forEach(Unknown Source)
		at net.fabricmc.loader.entrypoint.hooks.EntrypointUtils.logErrors(EntrypointUtils.java:36)
		... 19 more
	Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.api.event.client.ClientTickCallback
		at java.net.URLClassLoader.findClass(Unknown Source)
		at java.lang.ClassLoader.loadClass(Unknown Source)
		at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
		at java.lang.ClassLoader.loadClass(Unknown Source)
		at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:160)
		at java.lang.ClassLoader.loadClass(Unknown Source)
		... 24 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.fabricmc.loader.entrypoint.hooks.EntrypointUtils.logErrors(EntrypointUtils.java:45)
	at net.fabricmc.loader.entrypoint.hooks.EntrypointClient.start(EntrypointClient.java:35)
	at net.minecraft.class_310.method_1503(class_310.java)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.class_310.method_1514(class_310.java:395)
	at net.minecraft.client.main.Main.main(Main.java:154)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:129)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

**Comment by Naxanria** [comment]
Looks like you not have Fabric API installed: https://minecraft.curseforge.com/projects/fabric 
Just add it to the mods folder and it should work.
